### ISSUE TITLE
The grid does not load

### ISSUE THREAD

**Issue by McHeff** [EdCharbeneau/TelerikBlazorWasm#3]
Hi Ed, I've also tried to get a data grid using Kendo, but I cannot get it to load. I've cloned your project and see yours also just says "loading", do you know why? 

![image](https://user-images.githubusercontent.com/47241975/52400045-add7c100-2ac6-11e9-9173-a90e4551f03a.png)

Oh, I've made a discord server for Blazor if you'd be interested in joining: https://discord.gg/Xg9ja5s

**Comment by EdCharbeneau** [comment]
Correct. This is a repository I was using to troubleshoot this very issue. There is currently something in IL Linker that causes this. To fix the issue, simply disable the IL Linker. I had attempted to create a custom Linker in this project, but couldn't get it to work. I'll delete this repo soon since official examples will come online shortly.

**Comment by EdCharbeneau** [comment]
Add the following line to your .csproj file under `<LangVer..`

```
<BlazorLinkOnBuild>false</BlazorLinkOnBuild>
```

**Comment by McHeff** [comment]
I'm running on Blazor 0.7, not sure which .csproj file you're referring to?

**Comment by EdCharbeneau** [comment]
<yourproject>.Client.csproj

Ex: Like this but remove the `<!-- -->` comments
https://github.com/EdCharbeneau/TelerikBlazorWasm/blob/8a5f016fa26f57428ddd1973f0ca2061591e4483/TelerikBlazorWasm.Client/TelerikBlazorWasm.Client.csproj#L7

Blazor 0.7.0

**Comment by McHeff** [comment]
Ah cool! Thanks a lot Ed! Got it working... Now to getting a row's value working haha...
